[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config

#solc = "0.8.12" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`