[default]
src = 'src'
out = 'out'
libs = ['lib']
# Moved remappings to remappings.txt
# remappings = ['ds-test/=lib/ds-test/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config